### ISSUE TITLE
DOH Endpoint path is hard-coded

### ISSUE THREAD

**Issue by adam-burns** [shynome/doh-client#1]
Firstly, thank you for the project!

[RFC 8484 section 3](https://www.rfc-editor.org/rfc/rfc8484#section-3) states a DoH client is configured with a URI Template [[RFC6570](https://www.rfc-editor.org/rfc/rfc6570)], which describes how to construct the URL to use for resolution.

And more recently, [RFC9461](https://www.rfc-editor.org/rfc/rfc9461) introduces DNS specific SVCB resource records which can specify the path component of a DOH client configuration to use for a specific DOH server (see [Examples](https://www.rfc-editor.org/rfc/rfc9461#name-examples) section).

So, [hardcoded](https://github.com/shynome/doh-client/blob/3b78e35dadc53df5cf253bde3692e59507584a92/conn.go#L30),  the doh-client will work for the defacto example path value of "/dns-query", but will break for any other configuration of DOH server and any other advertised path component template.

**Comment by shynome** [comment]
Thanks for your issue, it has been fixed [support custom endpoint](https://github.com/shynome/doh-client/commit/5d1eb76d85f647f674870bc43c50fbb6f75dff8a)

**Comment by adam-burns** [comment]
Many thanks for your prompt attention on this issue.
